language: php
php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3
#  - hhvm

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script:
  - cd build; phing install-dependencies
  - cd build/ci; ant build

notifications:
  on_success: never
  on_failure: always
